[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build && npm run migration:create"

[deploy]
startCommand = "npm run migration:run && npm run start:prod"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10